version: "1"
services:
  node-express:
    image: node:latest
    container_name: node-express
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo